import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageType = "en" | "hi";

interface LanguageContextProps {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageType, Record<string, string>> = {
  en: {
    // Navigation / Sidebar
    "nav.dashboard": "Dashboard",
    "nav.report": "Report Issue",
    "nav.map": "Live Map",
    "nav.tracker": "Tracker",
    "nav.leaderboard": "Leaderboard",
    "nav.assistant": "AI Assistant",
    "sidebar.viewMode": "View Mode",
    "sidebar.citizen": "Citizen Hub",
    "sidebar.officer": "Officer Panel",
    "sidebar.signIn": "Initialize Identity",
    "sidebar.signOut": "Sign Out",
    "sidebar.municipalSuite": "MUNICIPAL INTELLIGENCE SUITE",
    "sidebar.officerCommandBoard": "MUNICIPAL OFFICER COMMAND BOARD: Direct write & status progression override parameters active.",

    // Dashboard Hero / Header
    "hero.title": "Accelerated Civic Resolution",
    "hero.desc": "Consolidating city complaints seamlessly. File grievances with image capture proof, allow Gemini's cognitive layer to isolate duplicate submissions, routing officers automatically to solve local hazards.",
    "hero.btn.report": "Report New Incident",
    "hero.btn.assistant": "Query AI Assistant",
    "banner.duplicateIsolation": "Gemini Duplicate Isolation",
    "banner.duplicateDesc": "To optimize municipal labor, reports created within 200m of an unresolved incident are scanned by Gemini. If determined as a duplicate, they are linked under a unified Support Ticket array instead of creating a separate standalone record.",
    "banner.escalateTriggers": "Dynamic Escalate Triggers",
    "banner.escalateDesc": "As nearby residents log similar duplicate files, verification tallies grow instantly. Tickets exceeding local weight indices trigger immediate L1, L2, or L3 escalation states, signaling officials with high-priority dashboard notifications.",

    // Stats Dashboard Widgets
    "stats.unresolved": "Unresolved Hazards",
    "stats.review": "Under Review",
    "stats.escalated": "Sovereign Escalated",
    "stats.resolved": "Community Resolved",
    "stats.totalReports": "Total Citizen Reports",
    "stats.coSigners": "Resident Co-Signers",
    "stats.resolvedCases": "Resolved Cases",
    "stats.rate": "Rate",
    "stats.closedVerified": "Closed & Verified",
    "stats.avgSla": "Avg SLA Closure",
    "stats.activeEscalations": "Active Escalations",
    "stats.tiersTriggered": "Tiers L1-L3 Triggered",
    "stats.byCategory": "Reports by Category",
    "stats.categoryDesc": "Distribution of public safety hazards",
    "stats.byStatus": "Reports by Status",
    "stats.statusDesc": "Operational SLA workflow levels",
    "stats.liveTrends": "NagarSevak Live Trends",
    "stats.aiScanner": "AI Anomaly Scanner Active",
    "stats.wardScorecard": "Ward Performance Scorecard",
    "stats.accountabilityGrid": "Public Accountability Grid",
    "stats.rankWard": "Rank & Ward Region",
    "stats.fileCounts": "Ununified File Counts",
    "stats.avgSpeed": "Avg Resolution Speed",
    "stats.slaCompliance": "SLA Compliance",
    "stats.responsibleOfficer": "Responsible Executive Officer",
    "stats.status": "Status",
    "stats.activeWardGrids": "Active Ward Grids",
    "stats.performanceMetric": "Performance metric within bounds",
    "stats.noTicketsFiled": "No tickets filed to catalog distribution",
    "stats.noStatusActive": "No status variables active",
    "stats.hours": "Hours",
    "stats.days": "Days",
    "stats.cases": "Cases",
    "stats.excellent": "Excellent",
    "stats.nominal": "Nominal",
    "stats.critical": "Critical",

    "stats.trend.trend-1.title": "Spike Registered",
    "stats.trend.trend-1.desc": "Unusual concentration of reports registered inside Ward boundaries this week.",
    "stats.trend.trend-2.title": "Collective Petitions Merged",
    "stats.trend.trend-2.desc": "SevakAI matched spatial grids nearby and automatically merged duplicate tickets to save municipal manpower.",
    "stats.trend.trend-3.title": "Resolution Latency Decreased",
    "stats.trend.trend-3.desc": "Average SLA closure times decreased by 14.5% due to proactive ward engineer deployment.",

    // Live Map
    "map.filters": "Filters:",
    "map.all": "All Cases",
    "map.potholes": "Potholes",
    "map.waterLeaks": "Water Leaks",
    "map.garbage": "Garbage & Sanitation",
    "map.streetlights": "Streetlights",
    "map.prophet": "Pothole Prophet",
    "map.prophetDesc": "Cluster Density Overlays",
    "map.legend": "Map Legend",
    "map.resolved": "Resolved",
    "map.filed": "Filed",
    "map.inProgress": "In Progress",
    "map.escalated": "Escalated",
    "map.verification": "Verification",
    "map.mockActive": "Mock Grid Active",
    "map.mockDesc": "To load actual satellite Google Maps, add your GOOGLE_MAPS_PLATFORM_KEY in the project secrets.",
    "map.noSignal": "No Signal Selected",
    "map.noSignalDesc": "Select a municipal marker on the map to inspect real-time photographic proof, SLA counters, and escalation traces.",
    "map.noImage": "No Image Evidence",
    "map.impact": "Impact:",
    "map.location": "Location:",
    "map.filingAge": "Filing Age:",
    "map.verifications": "Verifications:",
    "map.approved": "Approved",
    "map.supportAction": "Support Civic Action",

    // Report Grievance Form
    "form.header": "SUBMIT NEW CIVIC COMPLAINT",
    "form.uploadHeader": "Upload Incident Evidence",
    "form.dragDrop": "Drag and drop or click to upload JPEG/PNG showing current physical road or municipal hazard",
    "form.titleLabel": "Title",
    "form.titlePlaceholder": "e.g., Massive Pothole in Middle of Sector 4 Main Road",
    "form.descLabel": "Description",
    "form.descPlaceholder": "Describe the location details, landmark, and the precise hazard to help our municipal engineering department identify and dispatch.",
    "form.categoryLabel": "Select Hazard Category",
    "form.severityLabel": "Visual Severity Rating",
    "form.gpsLabel": "GPS Target Locking (Auto-Resolved)",
    "form.gpsDetecting": "Auto-detecting GPS coordinates...",
    "form.submitVerified": "Submit Verified Citizen Complaint",
    "form.submitGuest": "Submit as Guest Citizen",
    "form.listening": "Listening...",
    "form.voiceBtn": "Voice Input (Hindi/English)",
    "form.successHeader": "Grievance Registered Successfully",
    "form.duplicateMerged": "Duplicate Merged",
    "form.casePrefix": "Case #",
    "form.slaRoute": "is now locked into Municipal SLA routing.",
    "form.mergedCoPet": "Merged Co-Petitioner Network",
    "form.mergedDesc": "A matching hazard ticket is already active nearby. To prevent work-order duplication, your report has been merged with this high-priority ticket, adding you as an official co-reporter.",
    "form.visualAudit": "SevakAI Visual Audit",
    "form.assignedCat": "Assigned Category",
    "form.severityGauge": "Visual Severity Gauge",
    "form.sceneAnalysis": "Visual Scene Analysis",
    "form.resolvedJuris": "Resolved Jurisdiction",
    "form.assignedWard": "Assigned Ward / Zone",
    "form.responsibleBody": "Responsible Body",
    "form.officerEngineer": "Designated Officer / Engineer",
    "form.slaWindow": "SLA Resolution Window",
    "form.draftGriev": "Drafted Grievance Petitions",
    "form.syncPortal": "Synchronized with petition portal. PDF copy routed.",
    "form.copied": "Copied!",
    "form.copyBtn": "Copy Letter",

    // Case Tracker
    "tracker.header": "Live Case Tracker",
    "tracker.desc": "Delivery-style order tracking & autonomous legal branch escalation trace logs",
    "tracker.sync": "Realtime Sync Active",
    "tracker.filterAll": "All Active Grievances",
    "tracker.filterMine": "My Filed Cases",
    "tracker.resolvedBadge": "RESOLVED",
    "tracker.commVerified": "Community Verified ✓",
    "tracker.exactAddr": "Exact Address / Landmark",
    "tracker.filedDate": "Filed Date",
    "tracker.residentScore": "Resident Verification Index",
    "tracker.residents": "Residents",
    "tracker.verifiedMe": "Verified By Me",
    "tracker.verifyGrievance": "Verify Grievance",
    "tracker.verifying": "Verifying...",
    "tracker.simulate3": "Simulate 3 Verifications",
    "tracker.simulating": "Simulating...",
    "tracker.simulateEsc": "Simulate SLA Breach Escalation",
    "tracker.resolvedProof": "Resolved & Verified Proof",
    "tracker.before": "Before",
    "tracker.after": "After",
    "tracker.officialLog": "Judiciary Escalation Log & Sovereign Letters",
    "tracker.noHistory": "This report is currently operating within standard SLA limits. No escalation actions triggered.",
    "tracker.resolveForm": "Officer Resolution & Verification Panel",
    "tracker.uploadAfter": "Upload Resolution Proof Photo",
    "tracker.resolutionNotes": "Enter final resolution work log comments...",
    "tracker.submitResolve": "Submit Resolution & Verify Work",
    "tracker.rejectResolve": "Reject & Demand Rework",

    // Leaderboard
    "leaderboard.title": "Citizen Civic Leaderboard",
    "leaderboard.subtitle": "Top contributing citizens based on validated report filings and verified community contributions.",
    "leaderboard.score": "Civic Score",
    "leaderboard.ward": "Ward",
    "leaderboard.filed": "Reports Filed",
    "leaderboard.verified": "Reports Verified",
    "leaderboard.rank": "Rank",
    "leaderboard.citizen": "Citizen",
    "leaderboard.loading": "Retrieving dynamic leaderboard credentials...",
    "leaderboard.you": "YOU",
    "leaderboard.more": "more",
    "leaderboard.scoreCol": "Score",
    "leaderboard.earnedCol": "Earned Badges",
    "leaderboard.filedCol": "Reports",
    "leaderboard.filedCount": "filed",
    "leaderboard.civicPts": "Civic pts",
    "leaderboard.level3": "Level 3 Contributor",
    "leaderboard.badgeInventory": "Active Badge Inventory",
    "leaderboard.noBadges": "No active badges unlocked yet.",
    "leaderboard.rankMessage": "You are currently ranked #{rank} out of all participating citizens in your district.",
    "leaderboard.activeStreak": "Active Streak",
    "leaderboard.patrol": "day patrol",
    "leaderboard.personalImpact": "Personal Impact",
    "leaderboard.fixedIssues": "Fixed Issues",
    "leaderboard.standings": "District Civic Standings",
    "leaderboard.monthlyActive": "Monthly Active Grid",
    "leaderboard.earnedBadges": "Earned Badges",
    "leaderboard.unlocked": "Unlocked",
    "leaderboard.locked": "Locked",
    "leaderboard.requirement": "Requirement",
    "leaderboard.earnableBadges": "Earnable Civic Badges",
    "leaderboard.badgeShowcase": "Badge Showcase",
    "leaderboard.badgeShowcaseDesc": "Earn and unlock specific physical and digital badge credentials by executing civic responsibility. Unlocked badges will show on your profile and leaderboards.",
    "leaderboard.ledgerTitle": "Civic Point Ledger Structure",
    "leaderboard.rules": "Rules of Engagement",
    "leaderboard.actionCol": "Action / Contribution",
    "leaderboard.pointsCol": "Points Awarded",
    "leaderboard.frequencyCol": "Frequency cap",
    "leaderboard.descCol": "Description & Accountability Guidelines",
    "badge.potholeHunter.name": "Pothole Hunter",
    "badge.potholeHunter.desc": "Submit 5 pothole reports with GPS tags",
    "badge.potholeHunter.req": "5 Pothole Reports",
    "badge.lightGuardian.name": "Street Light Guardian",
    "badge.lightGuardian.desc": "Submit 3 streetlight/dark-spot reports",
    "badge.lightGuardian.req": "3 Streetlight Reports",
    "badge.wardChampion.name": "Ward Champion",
    "badge.wardChampion.desc": "Unlock by having the most active reports in your Ward",
    "badge.wardChampion.req": "Most Reports in Ward",
    "badge.firstResponder.name": "First Responder",
    "badge.firstResponder.desc": "Help verify 10 nearby reports using camera",
    "badge.firstResponder.req": "Verify 10 Reports",
    "badge.streakMaster.name": "Streak Master",
    "badge.streakMaster.desc": "Maintain a 30-day civic reporting/verification streak",
    "badge.streakMaster.req": "30-Day Streak",
    "ledger.report.action": "Report Municipal Issue",
    "ledger.report.desc": "Awarded immediately upon successful GPS tagging and submitting clear photographic evidence.",
    "ledger.report.freq": "Per unique ticket",
    "ledger.verify.action": "Help Verify Citizen Report",
    "ledger.verify.desc": "Submit corroborating on-site photo verification using SevakAI's camera framework.",
    "ledger.verify.freq": "No limit",
    "ledger.resolve.action": "Issue Successfully Resolved",
    "ledger.resolve.desc": "Extra points unlocked when ward engineers complete their SLA and close your reported hazard.",
    "ledger.resolve.freq": "Per resolved case",
    "ledger.streak.action": "Patrol Streak Multiplier",
    "ledger.streak.desc": "Maintain constant verification/reporting activity in the Ward to multiply default score counts.",
    "ledger.streak.freq": "Every 7 days",
    "ledger.merge.action": "Merge Duplicate Reports",
    "ledger.merge.desc": "Helped SevakAI consolidation algorithm detect nearby duplicate files to save ward workspace density.",
    "ledger.merge.freq": "Per consolidation",

    // AI Assistant
    "assistant.title": "NagarSevak Cognitive AI Assistant",
    "assistant.subtitle": "Ask about municipal rules, SLA status, or get legal support for your neighborhood issues in English or Hindi.",
    "assistant.placeholder": "Ask anything about municipal issues, SLAs, or file statuses...",
    "assistant.send": "Send Query",
    "assistant.welcome": "Namaste! I am SevakAI, your autonomous municipal concierge. I can analyze local case metrics, help parse public service SLAs, or explain how to accelerate resolving community hazards. How can I assist you today?",
    "assistant.suggestedQuestions": "Suggested Questions",
    "assistant.counselor": "SEVAKAI COUNSELOR",
    "assistant.knowledgeGraph": "Civic Knowledge-Graph Enabled",
    "assistant.assistantLevel": "Ward Assistant Level 1",
    "assistant.thinking": "SevakAI is thinking...",
    "assistant.error": "ERROR: Concluding your query failed. I am experiencing transient latency. Please submit your critical reports directly to the grievance feed.",
    "assistant.citizen": "Citizen",
    "prompt.chemical": "How do I report a toxic chemical dump or garbage pile?",
    "prompt.highPriority": "What counts as a High Priority ticket?",
    "prompt.simulate": "How can I simulate resolving a ticket here?",
    "prompt.auditors": "Who audits reported issues on NagarSevak?",
  },
  hi: {
    // Navigation / Sidebar
    "nav.dashboard": "डैशबोर्ड",
    "nav.report": "शिकायत दर्ज करें",
    "nav.map": "लाइव मैप",
    "nav.tracker": "केस ट्रैकर",
    "nav.leaderboard": "लीडरबोर्ड",
    "nav.assistant": "एआई सहायक",
    "sidebar.viewMode": "देखने का मोड",
    "sidebar.citizen": "नागरिक हब",
    "sidebar.officer": "अधिकारी पैनल",
    "sidebar.signIn": "पहचान स्थापित करें",
    "sidebar.signOut": "लॉग आउट",
    "sidebar.municipalSuite": "नगरपालिका इंटेलिजेंस सुइट",
    "sidebar.officerCommandBoard": "नगरपालिका अधिकारी कमांड बोर्ड: प्रत्यक्ष लेखन और स्थिति प्रगति ओवरराइड पैरामीटर सक्रिय।",

    // Dashboard Hero / Header
    "hero.title": "त्वरित नागरिक निवारण",
    "hero.desc": "शहर की शिकायतों का सहजता से समेकन। फोटो साक्ष्य के साथ शिकायतें दर्ज करें, जैमिनी की संज्ञानात्मक परत को डुप्लिकेट सबमिशन को अलग करने दें, जिससे अधिकारी स्वचालित रूप से स्थानीय खतरों को हल करने के लिए निर्देशित हों।",
    "hero.btn.report": "नई शिकायत दर्ज करें",
    "hero.btn.assistant": "एआई सहायक से पूछें",
    "banner.duplicateIsolation": "जैमिनी डुप्लिकेट पृथक्करण",
    "banner.duplicateDesc": "नगरपालिका श्रम को अनुकूलित करने के लिए, किसी अनसुलझी घटना के 200 मीटर के भीतर बनाई गई रिपोर्टों को जैमिनी द्वारा स्कैन किया जाता है। यदि डुप्लिकेट के रूप में निर्धारित किया जाता है, तो उन्हें एक अलग स्टैंडअलोन रिकॉर्ड बनाने के बजाय एक एकीकृत सपोर्ट टिकट सरणी के तहत जोड़ा जाता है।",
    "banner.escalateTriggers": "गतिशील एस्केलेशन ट्रिगर",
    "banner.escalateDesc": "जैसे-जैसे आस-पास के निवासी समान डुप्लिकेट फाइलें दर्ज करते हैं, सत्यापन संख्या तुरंत बढ़ती है। स्थानीय भार सूचकांकों से अधिक होने वाले टिकट तत्काल L1, L2, या L3 एस्केलेशन राज्यों को ट्रिगर करते हैं, जिससे अधिकारियों को उच्च-प्राथमिकता वाले डैशबोर्ड सूचनाएं प्राप्त होती हैं।",

    // Stats Dashboard Widgets
    "stats.unresolved": "लंबित समस्याएं",
    "stats.review": "समीक्षाधीन",
    "stats.escalated": "उच्च अधिकारी को प्रेषित",
    "stats.resolved": "समुदाय द्वारा हल",
    "stats.totalReports": "कुल नागरिक शिकायतें",
    "stats.coSigners": "सह-हस्ताक्षरकर्ता नागरिक",
    "stats.resolvedCases": "हल किए गए मामले",
    "stats.rate": "दर",
    "stats.closedVerified": "बंद और सत्यापित",
    "stats.avgSla": "औसत एसएलए बंद होने की अवधि",
    "stats.activeEscalations": "सक्रिय एस्केलेशन",
    "stats.tiersTriggered": "L1-L3 स्तर ट्रिगर",
    "stats.byCategory": "श्रेणी के अनुसार रिपोर्ट",
    "stats.categoryDesc": "सार्वजनिक सुरक्षा खतरों का विवरण और वितरण",
    "stats.byStatus": "स्थिति के अनुसार रिपोर्ट",
    "stats.statusDesc": "परिचालन एसएलए वर्कफ़्लो स्तर",
    "stats.liveTrends": "नगरसेवक लाइव ट्रेंड्स",
    "stats.aiScanner": "एआई विसंगति स्कैनर सक्रिय",
    "stats.wardScorecard": "वार्ड प्रदर्शन स्कोरकार्ड",
    "stats.accountabilityGrid": "सार्वजनिक जवाबदेही ग्रिड",
    "stats.rankWard": "रैंक और वार्ड क्षेत्र",
    "stats.fileCounts": "कुल फाइलें",
    "stats.avgSpeed": "औसत समाधान गति",
    "stats.slaCompliance": "SLA अनुपालन",
    "stats.responsibleOfficer": "जिम्मेदार कार्यकारी अधिकारी",
    "stats.status": "स्थिति",
    "stats.activeWardGrids": "सक्रिय वार्ड ग्रिड",
    "stats.performanceMetric": "प्रदर्शन मीट्रिक सीमा के भीतर",
    "stats.noTicketsFiled": "वितरण दर्ज करने के लिए कोई शिकायत नहीं मिली है",
    "stats.noStatusActive": "कोई स्थिति चर सक्रिय नहीं है",
    "stats.hours": "घंटे",
    "stats.days": "दिन",
    "stats.cases": "मामले",
    "stats.excellent": "उत्कृष्ट",
    "stats.nominal": "सामान्य",
    "stats.critical": "गंभीर",

    "stats.trend.trend-1.title": "तेजी दर्ज की गई",
    "stats.trend.trend-1.desc": "इस सप्ताह वार्ड सीमाओं के भीतर रिपोर्टों की असामान्य सांद्रता दर्ज की गई है।",
    "stats.trend.trend-2.title": "सामूहिक याचिकाएं एकीकृत की गईं",
    "stats.trend.trend-2.desc": "सेवकएआई ने पास के स्थानिक ग्रिड का मिलान किया और नगरपालिका जनशक्ति को बचाने के लिए डुप्लिकेट टिकटों को स्वचालित रूप से मिला दिया।",
    "stats.trend.trend-3.title": "समाधान समय में कमी आई",
    "stats.trend.trend-3.desc": "सक्रिय वार्ड इंजीनियर तैनाती के कारण औसत एसएलए बंद होने के समय में 14.5% की कमी आई है।",

    // Live Map
    "map.filters": "फ़िल्टर:",
    "map.all": "सभी मामले",
    "map.potholes": "गड्ढे",
    "map.waterLeaks": "पानी का रिसाव",
    "map.garbage": "कचरा और स्वच्छता",
    "map.streetlights": "स्ट्रीटलाइट्स",
    "map.prophet": "पॉथोल प्रॉफेट (गड्ढा पैगंबर)",
    "map.prophetDesc": "क्लस्टर घनत्व ओवरले",
    "map.legend": "नक्शा संकेतक",
    "map.resolved": "समाधान संपन्न",
    "map.filed": "दर्ज किया गया",
    "map.inProgress": "प्रगति पर",
    "map.escalated": "प्रेषित",
    "map.verification": "सत्यापन",
    "map.mockActive": "कृत्रिम ग्रिड सक्रिय",
    "map.mockDesc": "वास्तविक उपग्रह गूगल मैप्स लोड करने के लिए, प्रोजेक्ट सीक्रेट्स में अपनी GOOGLE_MAPS_PLATFORM_KEY जोड़ें।",
    "map.noSignal": "कोई संकेतक चयनित नहीं",
    "map.noSignalDesc": "वास्तविक समय के फोटो साक्ष्य, एसएलए काउंटरों और एस्केलेशन ट्रैस का निरीक्षण करने के लिए नक्शे पर एक नगरपालिका मार्कर का चयन करें।",
    "map.noImage": "कोई छवि प्रमाण नहीं",
    "map.impact": "प्रभाव:",
    "map.location": "स्थान:",
    "map.filingAge": "दर्ज समय:",
    "map.verifications": "सत्यापन:",
    "map.approved": "स्वीकृत",
    "map.supportAction": "नागरिक कार्रवाई का समर्थन करें",

    // Report Grievance Form
    "form.header": "नई नागरिक शिकायत दर्ज करें",
    "form.uploadHeader": "घटना का साक्ष्य अपलोड करें",
    "form.dragDrop": "वर्तमान सड़क या नगरपालिका खतरे को दर्शाने वाली JPEG/PNG छवि अपलोड करने के लिए खींचें और छोड़ें या क्लिक करें",
    "form.titleLabel": "शीर्षक",
    "form.titlePlaceholder": "उदा. सेक्टर 4 की मुख्य सड़क के बीच में बड़ा गड्ढा",
    "form.descLabel": "विवरण",
    "form.descPlaceholder": "हमारी नगरपालिका इंजीनियरिंग विभाग को पहचानने और भेजने में मदद करने के लिए स्थान विवरण, लैंडमार्क और सटीक खतरे का वर्णन करें।",
    "form.categoryLabel": "खतरे की श्रेणी चुनें",
    "form.severityLabel": "दृश्य तीव्रता रेटिंग",
    "form.gpsLabel": "जीपीएस टारगेट लॉकिंग (स्वतः निर्धारित)",
    "form.gpsDetecting": "जीपीएस निर्देशांकों का स्वतः पता लगाया जा रहा है...",
    "form.submitVerified": "सत्यापित नागरिक शिकायत दर्ज करें",
    "form.submitGuest": "अतिथि नागरिक के रूप में दर्ज करें",
    "form.listening": "सुन रहा हूँ...",
    "form.voiceBtn": "आवाज इनपुट (हिंदी/अंग्रेजी)",
    "form.successHeader": "शिकायत सफलतापूर्वक पंजीकृत की गई",
    "form.duplicateMerged": "डुप्लिकेट शिकायत एकीकृत",
    "form.casePrefix": "मामला संख्या #",
    "form.slaRoute": "अब नगरपालिका एसएलए रूटिंग में लॉक कर दिया गया है।",
    "form.mergedCoPet": "एकीकृत सह-याचिकाकर्ता नेटवर्क",
    "form.mergedDesc": "आस-पास एक समान खतरा टिकट पहले से ही सक्रिय है। काम के दोहराव को रोकने के लिए, आपकी रिपोर्ट को इस उच्च-प्राथमिकता वाले टिकट के साथ जोड़ दिया गया है, जिससे आप एक आधिकारिक सह-रिपोर्टर बन गए हैं।",
    "form.visualAudit": "सेवकएआई दृश्य ऑडिट",
    "form.assignedCat": "आवंटित श्रेणी",
    "form.severityGauge": "दृश्य तीव्रता सूचक",
    "form.sceneAnalysis": "दृश्य विश्लेषण",
    "form.resolvedJuris": "निर्धारित क्षेत्राधिकार",
    "form.assignedWard": "आवंटित वार्ड / क्षेत्र",
    "form.responsibleBody": "जिम्मेदार संस्था",
    "form.officerEngineer": "नामित अधिकारी / अभियंता",
    "form.slaWindow": "SLA समाधान समय-सीमा",
    "form.draftGriev": "तैयार की गई शिकायत याचिकाएं",
    "form.syncPortal": "शिकायत पोर्टल के साथ सिंक्रनाइज़ किया गया। पीडीएफ कॉपी भेजी गई।",
    "form.copied": "कॉपी किया गया!",
    "form.copyBtn": "पत्र कॉपी करें",

    // Case Tracker
    "tracker.header": "लाइव केस ट्रैकर",
    "tracker.desc": "डिलीवरी-शैली ऑर्डर ट्रैकिंग और स्वायत्त एस्केलेशन ट्रेस लॉग",
    "tracker.sync": "रीयल-टाइम सिंक सक्रिय",
    "tracker.filterAll": "सभी सक्रिय शिकायतें",
    "tracker.filterMine": "मेरे द्वारा दर्ज मामले",
    "tracker.resolvedBadge": "समाधान संपन्न",
    "tracker.commVerified": "समुदाय द्वारा सत्यापित ✓",
    "tracker.exactAddr": "सटीक स्थान / लैंडमार्क",
    "tracker.filedDate": "दर्ज करने की तिथि",
    "tracker.residentScore": "नागरीक सत्यापन सूचकांक",
    "tracker.residents": "निवासी",
    "tracker.verifiedMe": "मेरे द्वारा सत्यापित",
    "tracker.verifyGrievance": "शिकायत सत्यापित करें",
    "tracker.verifying": "सत्यापित किया जा रहा है...",
    "tracker.simulate3": "3 सत्यापन सिमुलेट करें",
    "tracker.simulating": "सिमुलेट किया जा रहा है...",
    "tracker.simulateEsc": "SLA उल्लंघन एस्केलेशन सिमुलेट करें",
    "tracker.resolvedProof": "समाधान और सत्यापित साक्ष्य",
    "tracker.before": "पहले",
    "tracker.after": "बाद में",
    "tracker.officialLog": "न्यायिक एस्केलेशन लॉग और संप्रभु पत्र",
    "tracker.noHistory": "यह रिपोर्ट वर्तमान में मानक एसएलए सीमाओं के भीतर काम कर रही है। कोई एस्केलेशन कार्रवाई शुरू नहीं की गई है।",
    "tracker.resolveForm": "अधिकारी समाधान और सत्यापन पैनल",
    "tracker.uploadAfter": "समाधान प्रमाण फोटो अपलोड करें",
    "tracker.resolutionNotes": "अंतिम समाधान कार्य लॉग टिप्पणियाँ दर्ज करें...",
    "tracker.submitResolve": "समाधान प्रस्तुत करें और कार्य सत्यापित करें",
    "tracker.rejectResolve": "अस्वीकार करें और दोबारा काम की मांग करें",

    // Leaderboard
    "leaderboard.title": "नागरिक नागरिक लीडरबोर्ड",
    "leaderboard.subtitle": "मान्य रिपोर्ट फाइलिंग और सत्यापित सामुदायिक योगदान के आधार पर शीर्ष योगदान देने वाले नागरिक।",
    "leaderboard.score": "नागरिक स्कोर",
    "leaderboard.ward": "वार्ड",
    "leaderboard.filed": "दर्ज शिकायतें",
    "leaderboard.verified": "सत्यापित शिकायतें",
    "leaderboard.rank": "रैंक",
    "leaderboard.citizen": "नागरिक",
    "leaderboard.loading": "गतिशील लीडरबोर्ड क्रेडेंशियल पुनः प्राप्त किया जा रहा है...",
    "leaderboard.you": "आप",
    "leaderboard.more": "और",
    "leaderboard.scoreCol": "स्कोर",
    "leaderboard.earnedCol": "अर्जित बैज",
    "leaderboard.filedCol": "रिपोर्ट",
    "leaderboard.filedCount": "दर्ज",
    "leaderboard.civicPts": "नागरिक अंक",
    "leaderboard.level3": "स्तर 3 योगदानकर्ता",
    "leaderboard.badgeInventory": "सक्रिय बैज सूची",
    "leaderboard.noBadges": "अभी तक कोई सक्रिय बैज अनलॉक नहीं हुआ है।",
    "leaderboard.rankMessage": "आप वर्तमान में अपने जिले के सभी भाग लेने वाले नागरिकों में #{rank} स्थान पर हैं।",
    "leaderboard.activeStreak": "सक्रिय सिलसिला",
    "leaderboard.patrol": "दिन की गश्त",
    "leaderboard.personalImpact": "व्यक्तिगत प्रभाव",
    "leaderboard.fixedIssues": "सुलझाए गए मुद्दे",
    "leaderboard.standings": "जिला नागरिक स्थिति",
    "leaderboard.monthlyActive": "मासिक सक्रिय ग्रिड",
    "leaderboard.earnedBadges": "अर्जित बैज",
    "leaderboard.unlocked": "अनलॉक किया गया",
    "leaderboard.locked": "लॉक किया गया",
    "leaderboard.requirement": "आवश्यकता",
    "leaderboard.earnableBadges": "अर्जित करने योग्य नागरिक बैज",
    "leaderboard.badgeShowcase": "बैज प्रदर्शन",
    "leaderboard.badgeShowcaseDesc": "नागरिक जिम्मेदारी निभाकर विशिष्ट भौतिक और डिजिटल बैज क्रेडेंशियल अर्जित और अनलॉक करें। अनलॉक किए गए बैज आपकी प्रोफ़ाइल और लीडरबोर्ड पर दिखाई देंगे।",
    "leaderboard.ledgerTitle": "नागरिक बिंदु बहीखाता संरचना",
    "leaderboard.rules": "सहभागिता के नियम",
    "leaderboard.actionCol": "कार्रवाई / योगदान",
    "leaderboard.pointsCol": "दिए गए अंक",
    "leaderboard.frequencyCol": "आवृत्ति सीमा",
    "leaderboard.descCol": "विवरण और जवाबदेही दिशानिर्देश",
    "badge.potholeHunter.name": "गड्ढा शिकारी",
    "badge.potholeHunter.desc": "जीपीएस टैग के साथ 5 गड्ढों की रिपोर्ट दर्ज करें",
    "badge.potholeHunter.req": "5 गड्ढों की रिपोर्ट",
    "badge.lightGuardian.name": "स्ट्रीट लाइट रक्षक",
    "badge.lightGuardian.desc": "3 स्ट्रीटलाइट/अंधेरे स्थानों की रिपोर्ट दर्ज करें",
    "badge.lightGuardian.req": "3 स्ट्रीटलाइट रिपोर्ट",
    "badge.wardChampion.name": "वार्ड चैंपियन",
    "badge.wardChampion.desc": "अपने वार्ड में सबसे अधिक सक्रिय रिपोर्ट दर्ज करके अनलॉक करें",
    "badge.wardChampion.req": "वार्ड में सर्वाधिक रिपोर्ट",
    "badge.firstResponder.name": "प्रथम प्रतिक्रियाकर्ता",
    "badge.firstResponder.desc": "कैमरे का उपयोग करके आस-पास की 10 रिपोर्ट सत्यापित करने में मदद करें",
    "badge.firstResponder.req": "10 रिपोर्ट सत्यापित करें",
    "badge.streakMaster.name": "सिलसिला मास्टर",
    "badge.streakMaster.desc": "30 दिनों का निरंतर नागरिक रिपोर्टिंग/सत्यापन का सिलसिला बनाए रखें",
    "badge.streakMaster.req": "30-दिन का सिलसिला",
    "ledger.report.action": "नगरपालिका समस्या की रिपोर्ट करें",
    "ledger.report.desc": "सफल जीपीएस टैगिंग और स्पष्ट फोटो प्रमाण जमा करने पर तुरंत प्रदान किया जाता है।",
    "ledger.report.freq": "प्रति विशिष्ट टिकट",
    "ledger.verify.action": "नागरिक रिपोर्ट सत्यापित करने में मदद करें",
    "ledger.verify.desc": "सेवकएआई के कैमरा फ्रेमवर्क का उपयोग करके ऑन-साइट फोटो सत्यापन जमा करें।",
    "ledger.verify.freq": "कोई सीमा नहीं",
    "ledger.resolve.action": "समस्या सफलतापूर्वक हल हुई",
    "ledger.resolve.desc": "जब वार्ड इंजीनियर अपना एसएलए पूरा करते हैं और आपके द्वारा रिपोर्ट किए गए खतरे को बंद करते हैं, तो अतिरिक्त अंक अनलॉक होते हैं।",
    "ledger.resolve.freq": "प्रति हल मामला",
    "ledger.streak.action": "गश्त सिलसिला गुणक",
    "ledger.streak.desc": "डिफ़ॉल्ट स्कोर संख्या को गुणा करने के लिए वार्ड में निरंतर सत्यापन/रिपोर्टिंग गतिविधि बनाए रखें।",
    "ledger.streak.freq": "प्रत्येक 7 दिन",
    "ledger.merge.action": "समान रिपोर्टों का विलय करें",
    "ledger.merge.desc": "सेवकएआई एकीकरण एल्गोरिदम को आस-पास के डुप्लिकेट फाइलों का पता लगाने में मदद की ताकि काम आसान हो सके।",
    "ledger.merge.freq": "प्रति विलय",

    // AI Assistant
    "assistant.title": "नगरसेवक संज्ञानात्मक एआई सहायक",
    "assistant.subtitle": "अंग्रेजी या हिंदी में अपने पड़ोस के मुद्दों के लिए नगरपालिका नियमों, एसएलए स्थिति के बारे में पूछें या कानूनी सहायता प्राप्त करें।",
    "assistant.placeholder": "नगरपालिका मुद्दों, एसएलए, या मामले की स्थिति के बारे में कुछ भी पूछें...",
    "assistant.send": "प्रश्न भेजें",
    "assistant.welcome": "नमस्ते! मैं सेवकएआई हूँ, आपका स्वायत्त नगरपालिका सहायक। मैं स्थानीय मामलों के आँकड़ों का विश्लेषण कर सकता हूँ, सार्वजनिक सेवा एसएलए को समझने में मदद कर सकता हूँ, या समझा सकता हूँ कि सामुदायिक खतरों के समाधान को कैसे तेज़ किया जाए। आज मैं आपकी किस प्रकार सहायता कर सकता हूँ?",
    "assistant.suggestedQuestions": "सुझाए गए प्रश्न",
    "assistant.counselor": "सेवकएआई सलाहकार",
    "assistant.knowledgeGraph": "नागरिक ज्ञान-ग्राफ सक्षम",
    "assistant.assistantLevel": "वार्ड सहायक स्तर 1",
    "assistant.thinking": "सेवकएआई सोच रहा है...",
    "assistant.error": "त्रुटि: आपकी क्वेरी पूरी करने में विफल। मैं अस्थायी विलंबता का अनुभव कर रहा हूँ। कृपया अपनी महत्वपूर्ण रिपोर्ट सीधे शिकायत फ़ीड में जमा करें।",
    "assistant.citizen": "नागरिक",
    "prompt.chemical": "मैं जहरीले रसायनों या कचरे के ढेर की रिपोर्ट कैसे करूँ?",
    "prompt.highPriority": "हाई प्रायोरिटी टिकट में क्या शामिल है?",
    "prompt.simulate": "मैं यहाँ टिकट के समाधान का अनुकरण कैसे करूँ?",
    "prompt.auditors": "नगरसेवक पर दर्ज समस्याओं का ऑडिट कौन करता है?",
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageType>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("nagarsevak_lang");
      if (saved === "hi" || saved === "en") return saved;
    }
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("nagarsevak_lang", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
